spring:
  application:
    name: Demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      idle-timeout: 10000
      connection-timeout: 30000
      auto-commit: false
      pool-name: engine_pool_demo
      minimum-idle: 5
    url: jdbc:mysql://localhost:3306/inkadiscount?useSSL=false
    username: inkafarma
    password: inkafarma

  jpa:
    # Show or not log for each sql query
    show-sql: true

    hibernate:
      # Hibernate ddl auto (create, create-drop, updateBO): with "updateBO" the database
      # schema will be automatically updated accordingly to java entities found in
      # the project
      ddl-auto: none

    properties:
      hibernate:
        # Naming strategy
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        # Allows Hibernate to generate SQL optimized for a particular DBMS
        dialect: org.hibernate.dialect.MySQL5Dialect